spring:
  profiles: security

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/brave
          jwk-set-uri: http://keycloak:8080/realms/brave/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
